### ISSUE TITLE
Define MVP, milestones and roadmap

### ISSUE THREAD

**Issue by ordepdev** [dembros/grasshopper#3]
We should define the project MVP, milestones, and roadmap.

**_MVP should include:_**
- [ ] HTTP Configuration
- [ ] Multiple HTTP Requests
- [ ] Each HTTP Request should log details somewhere
- [ ] Display HTTP Requests details
- [ ] ...

**_Nice to have:_**
- [ ] Dynamic concurrent calls (100 requests, wait 5 seconds, peak of 1000 requests)
- [ ] Real-time visualization
- [ ] ...

**_Requirements:_**
- [ ] Continuous Integration (Travis?)
- [ ] Automated code reviews (Codacy?)
- [ ] Automated releases (?)
- [ ] Coverage reports (Codecov?)
- [ ] Static analysis (?)
- [ ] Merge bot like Rultor (?)
- Github issue tracking always and for everything.
- ...

**_Stack:_**
- Gradle over Maven.
- Zero frameworks, only libraries. Spring what?
- Java? Scala?
- [Vertx and RxJava](http://vertx.io/docs/vertx-web-client/java/#_rxjava_api) for handling concurrent requests?
- ...

**Comment by ordepdev** [comment]
We should define the main goals and start creating issues.

**Comment by ordepdev** [comment]
@filfreire @hugomadureira please, pay attention to this issue!

**Comment by filfreire** [comment]
@ordepdev let's add to the Requirements list:
- Github issue tracking *always* and for everything. Each commit should point to an issue.
- Travis CI
- Automated releases
- Maybe a bot to do merges (that go through CI) and releases for us via comments in Github, like [rultor](github.com/yegor256/rultor)
- Coverage reports
- Static analysis (that makes the build fail) we could use [qulice](github.com/teamed/qulice)

**Comment by ordepdev** [comment]
@filfreire updated the requirements 👍
